	<!DOCTYPE html>
	<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>

		
	</head>
	<body>
		<div class="container-fluid">			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="navbar-brand" >Reporte Final Moviles</div>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="./index.html">
							Acerca de la aplicación 
							<span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="./code.html">Codigo</a>
						</li>
						<li class="nav-item active">
							<a class="nav-link" href="./eventual.html">Conectividad eventual</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="./desempenio.html">Desempeño</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="./alm.html">Almacenamiento y Seguridad</a>
						</li>
					</ul>
				</div>
			</nav>

			<br>
			<div class="container-fluid">
				<h2>Caso 1:</h2>
				<div class="container-fluid">
					<div class="row">
						<div class="col"> 
							<center><img src="./conectividad1.gif"></center>
						</div>
						<div class="col-9">
							<p>
								Se abrió la aplicación sin internet, como mantiene el usuario conectado pasa a la vita principal, pero al buscar una cerveza para hacer checkout la aplicaion falla y muestra un error genérico, dice que algo salió mal, pero ni el que ni el cómo arreglarlo. Lo cual es el anti-patrón de error genérico. 
							</p>
							<p>El mensaje de error ocurre debido una excepción sin controlar que sube hasta el genérico del widget y muestra el error sin ningún formato o mensaje claro.</p>
							<center><img src="./conectividad1.1.png"></center>
							<p>Cuando se llama al método que se encarga de buscar la implementación en especifica de la interfaz definida para  las consultas a bases de datos, se llama al método findBeersMatching, en este caso después de dos pasar por la implementación de dos interfaces la primera para datos externos en general y la segunda para datos de cervezas se llama al método correspondiente en la clase UntappdService. </p>
							<center><img src="./conectividad1.2.png"></center>
							<p>Como se puede observar el método tiene la verificación del tipo de respuesta por parte del servidor, y si es incorrecto lanza una excepción específica, sin  embargo en este caso el error ocurre en la línea donde se pide el request, el cual no esta en un Try por lo que la excepción lanzada es la que lanza el método getURL.</p>
							<center><img src="./conectividad1.3.png"></center>
							<p>Finalmente al no ser un error controlado, llega se cambia al estado con error y se muestra en pantalla.</p>
						</div>
					</div>
					
				</div>

				<br>
				<h2>Caso 2:</h2>
				<div class="container-fluid">
					<div class="row">
						<div class="col"> 
							<center><img src="./conectividad2.gif"></center>
						</div>
						<div class="col-9">
							<p>
								Pero luego al usarla esta se desconectó, como ya se vio en el caso si la aplicación esta sin internet y se busca algo  entonces la aplicación muestra un mensaje de error, pero si en lugar de eso solo se selecciona una cerveza de las recientes y se hace chekin, la aplicación permite hacerlo sin problemas, sin embargo el estado que se mantiene es el anterior al de hacer el cambio. Y no le notifico al usuario que paso.
							</p>
							<center><img src="./conectividad2.1.png"></center>
							<p>Tanto el historial como la página de perfil están constantemente escuchando un stream que recibe los chekin directamente desde el stream de firebase. Debido a que firebase puede manejar escenarios de conexión eventual por cuneta propia y que aun sin internet si los datos en cache cambian el stream recibe el cambio. El problema esta en la parte de hacer el chekin. Sin embargo el código de verificación del subir el chekin efectivamente tiene control de conectividad, mandando una excepción si no es posible.</p>
							<center><img src="./conectividad2.2.png"></center>
							<p>El problema es que aunque el método que llama al hacer chekin tiene un catch este lleva  una notificación a sentry más ningún cambio en pantalla por lo que el usuario no sabe que paso.</p>
							<center><img src="./conectividad2.3.png"></center>
							<center><img src="./conectividad2.4.png"></center>
						</div>
					</div>
					
				</div>
			</div>
			

			<footer class="page-footer font-small red">
				<div class="footer-copyright text-right py-3">Todos los datos en esta pagina fueron tomados en noviembre del 2019
				</div>
			</footer>
		</div>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	</body>
</body>
</html>